# Generated by Django 5.0.7 on 2026-08-18 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(db_comment="영업일자")),
                (
                    "open",
                    models.DecimalField(
                        db_comment="시가", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        db_comment="고가", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        db_comment="저가", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        db_comment="종가", decimal_places=2, max_digits=15
                    ),
                ),
                ("volume", models.BigIntegerField(db_comment="거래량", default=0)),
                (
                    "trade_amount",
                    models.BigIntegerField(
                        blank=True, db_comment="거래대금", null=True
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(auto_now=True, db_comment="수집시각"),
                ),
            ],
            options={
                "verbose_name": "일봉",
                "verbose_name_plural": "일봉",
                "db_table": '"investment_discipline"."market_daily_candles"',
            },
        ),
        migrations.CreateModel(
            name="KisToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "env",
                    models.CharField(
                        db_comment="환경(paper|live)", max_length=10, unique=True
                    ),
                ),
                ("access_token", models.TextField(db_comment="접근토큰")),
                ("expires_at", models.DateTimeField(db_comment="만료시각")),
                (
                    "approval_key",
                    models.CharField(
                        blank=True, db_comment="실시간접속키", max_length=200, null=True
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now=True, db_comment="발급시각"),
                ),
            ],
            options={
                "verbose_name": "KIS토큰",
                "verbose_name_plural": "KIS토큰",
                "db_table": '"investment_discipline"."market_kis_tokens"',
            },
        ),
        migrations.CreateModel(
            name="MinuteCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("ts", models.DateTimeField(db_comment="봉시작시각(UTC)")),
                (
                    "open",
                    models.DecimalField(
                        db_comment="시가", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        db_comment="고가", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        db_comment="저가", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        db_comment="종가", decimal_places=2, max_digits=15
                    ),
                ),
                ("volume", models.BigIntegerField(db_comment="거래량", default=0)),
                (
                    "collected_at",
                    models.DateTimeField(auto_now=True, db_comment="수집시각"),
                ),
            ],
            options={
                "verbose_name": "분봉",
                "verbose_name_plural": "분봉",
                "db_table": '"investment_discipline"."market_minute_candles"',
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("KOSPI", "코스피"),
                            ("KOSDAQ", "코스닥"),
                            ("KONEX", "코넥스"),
                            ("NASDAQ", "나스닥"),
                            ("NYSE", "뉴욕증권거래소"),
                            ("AMEX", "아멕스"),
                            ("ETC", "기타"),
                        ],
                        db_comment="시장",
                        default="KOSPI",
                        max_length=20,
                    ),
                ),
                ("symbol", models.CharField(db_comment="종목코드", max_length=30)),
                ("name", models.CharField(db_comment="종목명", max_length=200)),
                (
                    "is_subscribed",
                    models.BooleanField(db_comment="수집대상여부", default=True),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="최종조회가",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "last_price_at",
                    models.DateTimeField(
                        blank=True, db_comment="최종조회시각", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="수정일시"),
                ),
            ],
            options={
                "verbose_name": "수집종목",
                "verbose_name_plural": "수집종목",
                "db_table": '"investment_discipline"."market_symbols"',
                "indexes": [
                    models.Index(
                        fields=["is_subscribed"], name="market_symbol_subscribed_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="symbol",
            constraint=models.UniqueConstraint(
                fields=("market", "symbol"), name="market_symbol_uniq"
            ),
        ),
        migrations.AddField(
            model_name="minutecandle",
            name="symbol",
            field=models.ForeignKey(
                db_column="symbol_id",
                db_comment="종목ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minute_candles",
                to="market_data.symbol",
            ),
        ),
        migrations.AddField(
            model_name="dailycandle",
            name="symbol",
            field=models.ForeignKey(
                db_column="symbol_id",
                db_comment="종목ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_candles",
                to="market_data.symbol",
            ),
        ),
        migrations.AddIndex(
            model_name="minutecandle",
            index=models.Index(
                fields=["symbol", "-ts"], name="minute_candle_sym_ts_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="minutecandle",
            constraint=models.UniqueConstraint(
                fields=("symbol", "ts"), name="minute_candle_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="dailycandle",
            index=models.Index(
                fields=["symbol", "-date"], name="daily_candle_sym_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailycandle",
            constraint=models.UniqueConstraint(
                fields=("symbol", "date"), name="daily_candle_uniq"
            ),
        ),
    ]
