# Generated by Django 5.0.7 on 2026-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="symbol",
            name="market_symbol_subscribed_idx",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="is_subscribed",
        ),
        migrations.AddIndex(
            model_name="symbol",
            index=models.Index(fields=["symbol"], name="market_symbol_code_idx"),
        ),
    ]
