# Generated by Django 5.0.6 on 2026-08-10 02:20

import django.core.validators
import django.db.models.deletion
import trading_discipline.models.planning._mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrokerAccount",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "id",
                    models.AutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "broker_name",
                    models.CharField(
                        blank=True, db_comment="증권사명", max_length=100, null=True
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, db_comment="계좌번호", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "증권사계좌",
                "verbose_name_plural": "증권사계좌",
                "db_table": '"investment_discipline"."broker_accounts"',
            },
        ),
        migrations.CreateModel(
            name="MandatoryPrinciple",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(blank=True, db_comment="중요순위", null=True),
                ),
                ("content", models.TextField(blank=True, db_comment="내용", null=True)),
            ],
            options={
                "verbose_name": "나의필수원칙",
                "verbose_name_plural": "나의필수원칙",
                "db_table": '"investment_discipline"."mandatory_principles"',
                "ordering": ("priority", "id"),
            },
        ),
        migrations.CreateModel(
            name="PrincipleSource",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="원칙소스ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_comment="소스명", max_length=200, null=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOOK", "책"),
                            ("VIDEO", "영상"),
                            ("ARTICLE", "글"),
                            ("LECTURE", "강의"),
                            ("INTERVIEW", "인터뷰"),
                            ("PAPER", "논문/리포트"),
                            ("ETC", "기타"),
                        ],
                        db_comment="소스유형",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("url", models.TextField(blank=True, db_comment="소스URL", null=True)),
                ("content", models.TextField(blank=True, db_comment="내용", null=True)),
            ],
            options={
                "verbose_name": "투자원칙소스",
                "verbose_name_plural": "투자원칙소스",
                "db_table": '"investment_discipline"."principle_sources"',
            },
        ),
        migrations.CreateModel(
            name="AiModelRun",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, db_comment="모델명", max_length=200, null=True
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, db_comment="모델버전", max_length=100, null=True
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, db_comment="프롬프트버전", max_length=100, null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_comment="시작시각", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_comment="완료시각", null=True),
                ),
                (
                    "input_snapshot_json",
                    models.JSONField(blank=True, db_comment="입력스냅샷", null=True),
                ),
                (
                    "output_json",
                    models.JSONField(blank=True, db_comment="출력", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "대기"),
                            ("RUNNING", "실행중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                            ("CANCELED", "취소"),
                        ],
                        db_comment="상태",
                        default="PENDING",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI모델실행",
                "verbose_name_plural": "AI모델실행",
                "db_table": '"investment_discipline"."ai_model_runs"',
                "indexes": [
                    models.Index(
                        fields=["status", "-started_at"],
                        name="airun_status_started_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnnualInvestmentPlan",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("KOSPI", "코스피"),
                            ("KOSDAQ", "코스닥"),
                            ("KONEX", "코넥스"),
                            ("NASDAQ", "나스닥"),
                            ("NYSE", "뉴욕증권거래소"),
                            ("AMEX", "아멕스"),
                            ("ETC", "기타"),
                        ],
                        db_comment="시장",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(db_comment="계획명", max_length=200)),
                ("thesis", models.TextField(db_comment="투자논리")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("LONG", "매수"),
                            ("SHORT", "매도"),
                            ("NEUTRAL", "관망"),
                            ("HEDGE", "헤지"),
                        ],
                        db_comment="투자방향",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성중"),
                            ("ACTIVE", "진행중"),
                            ("PAUSED", "중단"),
                            ("CLOSED", "종료"),
                            ("ABANDONED", "폐기"),
                        ],
                        db_comment="계획상태",
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(db_comment="유효시작일")),
                ("valid_until", models.DateField(db_comment="유효종료일")),
                (
                    "target_return_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="목표수익비율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "stop_loss_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="손절비율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        db_comment="증권사계좌ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annual_plans",
                        to="trading_discipline.brokeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "연투자계획",
                "verbose_name_plural": "연투자계획",
                "db_table": '"investment_discipline"."annual_investment_plan"',
            },
            bases=(
                trading_discipline.models.planning._mixins.PlanPeriodMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MarketDirection",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UP", "상승"),
                            ("DOWN", "하락"),
                            ("SIDEWAYS", "횡보"),
                            ("VOLATILE", "변동성확대"),
                        ],
                        db_comment="방향",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "factor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RATE", "금리"),
                            ("FX", "환율"),
                            ("COMMODITY", "원자재"),
                            ("POLICY", "정책/규제"),
                            ("EARNINGS", "실적"),
                            ("GEOPOLITICS", "지정학"),
                            ("LIQUIDITY", "유동성"),
                            ("SENTIMENT", "투자심리"),
                        ],
                        db_comment="요인종류",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("content", models.TextField(blank=True, db_comment="내용", null=True)),
                (
                    "rationale",
                    models.TextField(blank=True, db_comment="투자근거", null=True),
                ),
                (
                    "factor_value",
                    models.DecimalField(
                        blank=True,
                        db_comment="수치",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "affected_targets",
                    models.JSONField(blank=True, db_comment="영향대상", null=True),
                ),
            ],
            options={
                "verbose_name": "시장방향",
                "verbose_name_plural": "시장방향",
                "db_table": '"investment_discipline"."market_directions"',
                "indexes": [
                    models.Index(
                        fields=["factor_type", "direction"], name="mdir_factor_dir_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestmentPrinciple",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="투자원칙ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True,
                        db_comment="원칙가르치는사람",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "principle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUY", "매수원칙"),
                            ("SELL", "매도원칙"),
                            ("RISK", "위험관리"),
                            ("VALUATION", "가치평가"),
                            ("PORTFOLIO", "포트폴리오"),
                            ("MINDSET", "태도"),
                        ],
                        db_comment="원칙종류",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("content", models.TextField(blank=True, db_comment="내용", null=True)),
                (
                    "rationale",
                    models.TextField(blank=True, db_comment="투자근거", null=True),
                ),
                (
                    "cautions",
                    models.TextField(blank=True, db_comment="주의사항", null=True),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_id",
                        db_comment="원칙소스ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="principles",
                        to="trading_discipline.principlesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "투자원칙",
                "verbose_name_plural": "투자원칙",
                "db_table": '"investment_discipline"."investment_principles"',
            },
        ),
        migrations.CreateModel(
            name="QuarterlyInvestmentPlan",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_comment="계획명", max_length=200)),
                (
                    "rebalancing_ratio",
                    models.JSONField(blank=True, db_comment="리벨런싱비율", null=True),
                ),
                (
                    "rebalancing_start_date",
                    models.DateField(
                        blank=True, db_comment="리벨런싱시작일", null=True
                    ),
                ),
                (
                    "rebalancing_end_date",
                    models.DateField(
                        blank=True, db_comment="리벨런싱종료일", null=True
                    ),
                ),
                (
                    "buy_strategy",
                    models.TextField(blank=True, db_comment="매수전략", null=True),
                ),
                (
                    "sell_strategy",
                    models.TextField(blank=True, db_comment="매도전략", null=True),
                ),
                (
                    "sideways_strategy",
                    models.TextField(blank=True, db_comment="횡보전략", null=True),
                ),
                (
                    "stop_loss_strategy",
                    models.TextField(blank=True, db_comment="손절전략", null=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("LONG", "매수"),
                            ("SHORT", "매도"),
                            ("NEUTRAL", "관망"),
                            ("HEDGE", "헤지"),
                        ],
                        db_comment="투자방향",
                        max_length=20,
                    ),
                ),
                ("thesis", models.TextField(db_comment="투자논리")),
                ("valid_from", models.DateField(db_comment="유효시작일")),
                ("valid_until", models.DateField(db_comment="유효종료일")),
                (
                    "target_return_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="목표수익비율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "stop_loss_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="손절비율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "annual_plan",
                    models.ForeignKey(
                        blank=True,
                        db_column="annual_plan_id",
                        db_comment="연계획ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarterly_plans",
                        to="trading_discipline.annualinvestmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "분기투자계획",
                "verbose_name_plural": "분기투자계획",
                "db_table": '"investment_discipline"."quarterly_investment_plan"',
            },
            bases=(
                trading_discipline.models.planning._mixins.PlanPeriodMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MonthlyInvestmentPlan",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_comment="계획명", max_length=200)),
                (
                    "scenario_planning",
                    models.CharField(
                        choices=[
                            ("BASE", "기본"),
                            ("BULL", "낙관"),
                            ("BEAR", "비관"),
                            ("STRESS", "악재"),
                        ],
                        db_comment="시나리오계획",
                        default="BASE",
                        max_length=20,
                    ),
                ),
                (
                    "predicted_trend",
                    models.CharField(
                        choices=[
                            ("UP", "상승"),
                            ("DOWN", "하락"),
                            ("SIDEWAYS", "횡보"),
                            ("VOLATILE", "변동성확대"),
                        ],
                        db_comment="예상추세",
                        max_length=20,
                    ),
                ),
                ("thesis", models.TextField(db_comment="투자논리")),
                (
                    "confidence_score",
                    models.IntegerField(
                        blank=True,
                        db_comment="계획확신도",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "allocation_ratio",
                    models.JSONField(blank=True, db_comment="벨런싱비율", null=True),
                ),
                ("valid_from", models.DateField(db_comment="유효시작일")),
                ("valid_until", models.DateField(db_comment="유효종료일")),
                (
                    "quarterly_plan",
                    models.ForeignKey(
                        blank=True,
                        db_column="quarterly_plan_id",
                        db_comment="분기계획ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_plans",
                        to="trading_discipline.quarterlyinvestmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "월투자계획",
                "verbose_name_plural": "월투자계획",
                "db_table": '"investment_discipline"."monthly_investment_plan"',
            },
            bases=(
                trading_discipline.models.planning._mixins.PlanPeriodMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("KOSPI", "코스피"),
                            ("KOSDAQ", "코스닥"),
                            ("KONEX", "코넥스"),
                            ("NASDAQ", "나스닥"),
                            ("NYSE", "뉴욕증권거래소"),
                            ("AMEX", "아멕스"),
                            ("ETC", "기타"),
                        ],
                        db_comment="시장",
                        max_length=20,
                    ),
                ),
                ("symbol", models.CharField(db_comment="종목코드", max_length=30)),
                ("name", models.CharField(db_comment="종목명", max_length=200)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "주식"),
                            ("ETF", "ETF"),
                            ("ETN", "ETN"),
                            ("REIT", "리츠"),
                            ("BOND", "채권"),
                            ("FUND", "펀드"),
                            ("CASH", "현금"),
                            ("CRYPTO", "가상자산"),
                        ],
                        db_comment="자산유형",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KRW", "원"),
                            ("USD", "달러"),
                            ("JPY", "엔"),
                            ("EUR", "유로"),
                            ("HKD", "홍콩달러"),
                            ("CNY", "위안"),
                        ],
                        db_comment="통화",
                        default="KRW",
                        max_length=3,
                    ),
                ),
                (
                    "holding_quantity",
                    models.IntegerField(blank=True, db_comment="보유개수", null=True),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="현재주가",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, db_comment="업종", max_length=100, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_comment="관리대상여부", default=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        db_comment="계좌ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="securities",
                        to="trading_discipline.brokeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "종목",
                "verbose_name_plural": "종목",
                "db_table": '"investment_discipline"."securities"',
            },
        ),
        migrations.CreateModel(
            name="SecuritiesLoan",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "id",
                    models.AutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        blank=True,
                        db_comment="대출원금",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        db_comment="이자율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "opened_at",
                    models.DateField(blank=True, db_comment="대출시작일", null=True),
                ),
                (
                    "maturity_at",
                    models.DateField(blank=True, db_comment="만기일", null=True),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, db_comment="담보수량", null=True),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="기준가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "collateral_value",
                    models.DecimalField(
                        blank=True,
                        db_comment="담보평가금액",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "collateral_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="담보비율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(blank=True, db_comment="평가시각", null=True),
                ),
                (
                    "security",
                    models.ForeignKey(
                        db_column="security_id",
                        db_comment="종목ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "종목담보대출",
                "verbose_name_plural": "종목담보대출",
                "db_table": '"investment_discipline"."securities_loans"',
            },
        ),
        migrations.CreateModel(
            name="QuarterlyInvestmentPrinciple",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "predicted_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="예상가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="손절가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        db_comment="매출액",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "revenue_growth_rate",
                    models.DecimalField(
                        blank=True,
                        db_comment="매출증가율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "new_orders_amount",
                    models.DecimalField(
                        blank=True,
                        db_comment="신규 수주액",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "order_backlog",
                    models.DecimalField(
                        blank=True,
                        db_comment="수주잔고",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        blank=True,
                        db_comment="영업이익률",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "net_income",
                    models.DecimalField(
                        blank=True,
                        db_comment="순이익",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        db_comment="ROE",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "roic",
                    models.DecimalField(
                        blank=True,
                        db_comment="ROIC",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "free_cash_flow",
                    models.DecimalField(
                        blank=True,
                        db_comment="잉여현금흐름",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "cash_conversion_rate",
                    models.DecimalField(
                        blank=True,
                        db_comment="현금전환율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "interest_coverage_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="이자보상배율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "per",
                    models.DecimalField(
                        blank=True,
                        db_comment="PER",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "pbr",
                    models.DecimalField(
                        blank=True,
                        db_comment="PBR",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ev_ebitda",
                    models.DecimalField(
                        blank=True,
                        db_comment="EV/EBITDA",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "psr",
                    models.DecimalField(
                        blank=True,
                        db_comment="PSR",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "fcf_yield",
                    models.DecimalField(
                        blank=True,
                        db_comment="FCF수익률",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "valuation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNDERVALUED", "저평가"),
                            ("FAIR", "적정"),
                            ("OVERVALUED", "고평가"),
                        ],
                        db_comment="기업가치종류",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "performance_summary",
                    models.TextField(blank=True, db_comment="실적", null=True),
                ),
                (
                    "quarterly_plan",
                    models.ForeignKey(
                        blank=True,
                        db_column="quarterly_plan_id",
                        db_comment="분기계획ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principles",
                        to="trading_discipline.quarterlyinvestmentplan",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        db_column="security_id",
                        db_comment="종목ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarterly_principles",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "분기투자원칙",
                "verbose_name_plural": "분기투자원칙",
                "db_table": '"investment_discipline"."quarterly_investment_principles"',
            },
        ),
        migrations.CreateModel(
            name="PerformanceRecord",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAY", "일"),
                            ("WEEK", "주"),
                            ("MONTH", "월"),
                            ("QUARTER", "분기"),
                            ("YEAR", "연"),
                        ],
                        db_comment="기간유형",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(blank=True, db_comment="기간시작일", null=True),
                ),
                (
                    "period_end",
                    models.DateField(blank=True, db_comment="기간종료일", null=True),
                ),
                (
                    "realized_profit",
                    models.DecimalField(
                        blank=True,
                        db_comment="실현손익",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "unrealized_profit",
                    models.DecimalField(
                        blank=True,
                        db_comment="평가손익",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "dividend_income",
                    models.DecimalField(
                        blank=True,
                        db_comment="배당수익",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "interest_cost",
                    models.DecimalField(
                        blank=True,
                        db_comment="이자비용",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        blank=True,
                        db_comment="수수료",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        db_comment="세금",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "etc_cost",
                    models.DecimalField(
                        blank=True,
                        db_comment="기티비용",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True,
                        db_comment="순손익",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "return_rate",
                    models.DecimalField(
                        blank=True,
                        db_comment="수익률",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "benchmark_return_rate",
                    models.DecimalField(
                        blank=True,
                        db_comment="벤치마크수익률",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True,
                        db_comment="최대낙폭",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        db_column="security_id",
                        db_comment="종목ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "성과",
                "verbose_name_plural": "성과",
                "db_table": '"investment_discipline"."performance_records"',
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLAN", "계획"),
                            ("ORDER", "주문"),
                            ("FILL", "체결"),
                            ("CANCEL", "취소"),
                            ("REJECT", "거부"),
                        ],
                        db_comment="행위종류",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MARKET", "시장가"),
                            ("LIMIT", "지정가"),
                            ("STOP", "역지정가"),
                            ("STOP_LIMIT", "역지정지정가"),
                            ("TRAILING", "추적손절"),
                        ],
                        db_comment="주문유형",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[("BUY", "매수"), ("SELL", "매도")],
                        db_comment="매수매도구분",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, db_comment="수량", null=True),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="지정가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, db_comment="이행시각", null=True),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        db_column="security_id",
                        db_comment="종목ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "이행",
                "verbose_name_plural": "이행",
                "db_table": '"investment_discipline"."orders"',
            },
        ),
        migrations.CreateModel(
            name="MonthlyInvestmentPrinciple",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LONG", "매수"),
                            ("SHORT", "매도"),
                            ("NEUTRAL", "관망"),
                            ("HEDGE", "헤지"),
                        ],
                        db_comment="투자방향",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(blank=True, db_comment="근거", null=True),
                ),
                (
                    "predicted_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="예상가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="손절가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "monthly_plan",
                    models.ForeignKey(
                        blank=True,
                        db_column="monthly_plan_id",
                        db_comment="월계획ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principles",
                        to="trading_discipline.monthlyinvestmentplan",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        db_column="security_id",
                        db_comment="종목ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_principles",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "월투자원칙",
                "verbose_name_plural": "월투자원칙",
                "db_table": '"investment_discipline"."monthly_investment_principles"',
            },
        ),
        migrations.CreateModel(
            name="AffectedSecurity",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="영향종목ID (DDL 에 없어 추가)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "market_direction",
                    models.ForeignKey(
                        blank=True,
                        db_column="market_directions_id",
                        db_comment="시장방향ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affected_securities",
                        to="trading_discipline.marketdirection",
                    ),
                ),
                (
                    "affected_security",
                    models.ForeignKey(
                        blank=True,
                        db_column="affected_security_id",
                        db_comment="영향받는종목ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_directions",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "영향종목",
                "verbose_name_plural": "영향종목",
                "db_table": '"investment_discipline"."affected_securities"',
            },
        ),
        migrations.CreateModel(
            name="SecurityPriceData",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "price_at",
                    models.DateTimeField(blank=True, db_comment="시각", null=True),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="고가",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="저가",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "quote_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="호가",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        db_column="security_id",
                        db_comment="종목ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_data",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "가격데이터",
                "verbose_name_plural": "가격데이터",
                "db_table": '"investment_discipline"."security_price_data"',
            },
        ),
        migrations.CreateModel(
            name="TradingStrategy",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "policy_name",
                    models.CharField(
                        blank=True, db_comment="정책명", max_length=200, null=True
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, db_comment="업종", max_length=100, null=True
                    ),
                ),
                (
                    "reference_at",
                    models.DateTimeField(blank=True, db_comment="기준시각", null=True),
                ),
                (
                    "price_data",
                    models.ForeignKey(
                        blank=True,
                        db_column="price_data_id",
                        db_comment="가격데이터ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="strategies",
                        to="trading_discipline.securitypricedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "매수매도전략",
                "verbose_name_plural": "매수매도전략",
                "db_table": '"investment_discipline"."trading_strategies"',
            },
        ),
        migrations.CreateModel(
            name="TradingStrategyMethod",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUY_SPLIT", "분할매수"),
                            ("SELL_SPLIT", "분할매도"),
                            ("ADD_ON", "추가매수"),
                            ("TAKE_PROFIT", "익절"),
                            ("STOP_LOSS", "손절"),
                        ],
                        db_comment="전략종류",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "step_no",
                    models.IntegerField(blank=True, db_comment="n차", null=True),
                ),
                (
                    "price_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="전략가격비율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "quantity_ratio",
                    models.DecimalField(
                        blank=True,
                        db_comment="전략수량비율",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, db_comment="업종", max_length=100, null=True
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        db_column="strategy_id",
                        db_comment="전략ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="trading_discipline.tradingstrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "매수매도방법",
                "verbose_name_plural": "매수매도방법",
                "db_table": '"investment_discipline"."trading_strategy_methods"',
                "ordering": ("strategy_id", "strategy_type", "step_no"),
            },
        ),
        migrations.CreateModel(
            name="WeeklyInvestmentPlan",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_comment="계획명", max_length=200)),
                (
                    "scenario_planning",
                    models.CharField(
                        choices=[
                            ("BASE", "기본"),
                            ("BULL", "낙관"),
                            ("BEAR", "비관"),
                            ("STRESS", "악재"),
                        ],
                        db_comment="시나리오계획",
                        default="BASE",
                        max_length=20,
                    ),
                ),
                (
                    "available_amount",
                    models.DecimalField(
                        blank=True,
                        db_comment="가용금액",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "predicted_trend",
                    models.CharField(
                        choices=[
                            ("UP", "상승"),
                            ("DOWN", "하락"),
                            ("SIDEWAYS", "횡보"),
                            ("VOLATILE", "변동성확대"),
                        ],
                        db_comment="예측추세",
                        max_length=20,
                    ),
                ),
                ("thesis", models.TextField(db_comment="투자논리")),
                (
                    "confidence_score",
                    models.IntegerField(
                        blank=True,
                        db_comment="계획확신도",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "allocation_ratio",
                    models.JSONField(
                        blank=True, db_comment="벨런싱비율계획", null=True
                    ),
                ),
                ("valid_from", models.DateField(db_comment="유효시작일")),
                ("valid_until", models.DateField(db_comment="유효종료일")),
                (
                    "predicted_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="예상가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="손절가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        db_column="security_id",
                        db_comment="종목ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_plans",
                        to="trading_discipline.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "주투자계획",
                "verbose_name_plural": "주투자계획",
                "db_table": '"investment_discipline"."weekly_investment_plan"',
            },
            bases=(
                trading_discipline.models.planning._mixins.PlanPeriodMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DailyInvestmentPlan",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_comment="계획명", max_length=200)),
                (
                    "scenario_planning",
                    models.CharField(
                        choices=[
                            ("BASE", "기본"),
                            ("BULL", "낙관"),
                            ("BEAR", "비관"),
                            ("STRESS", "악재"),
                        ],
                        db_comment="시나리오계획",
                        default="BASE",
                        max_length=20,
                    ),
                ),
                (
                    "predicted_trend",
                    models.CharField(
                        choices=[
                            ("UP", "상승"),
                            ("DOWN", "하락"),
                            ("SIDEWAYS", "횡보"),
                            ("VOLATILE", "변동성확대"),
                        ],
                        db_comment="예측추세",
                        max_length=20,
                    ),
                ),
                ("thesis", models.TextField(db_comment="투자논리")),
                (
                    "confidence_score",
                    models.IntegerField(
                        blank=True,
                        db_comment="계획확신도",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "allocation_ratio",
                    models.JSONField(
                        blank=True, db_comment="벨런싱비율계획", null=True
                    ),
                ),
                ("valid_from", models.DateField(db_comment="유효시작일")),
                ("valid_until", models.DateField(db_comment="유효종료일")),
                (
                    "predicted_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="예상가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="손절가격",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "weekly_plan",
                    models.ForeignKey(
                        blank=True,
                        db_column="weekly_plan_id",
                        db_comment="주계획ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_plans",
                        to="trading_discipline.weeklyinvestmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "일투자계획",
                "verbose_name_plural": "일투자계획",
                "db_table": '"investment_discipline"."daily_investment_plan"',
            },
            bases=(
                trading_discipline.models.planning._mixins.PlanPeriodMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="AiDecisionFeedback",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "opinion_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REVIEW", "검토"),
                            ("WARNING", "경고"),
                            ("SUGGESTION", "제안"),
                            ("APPROVAL", "동의"),
                            ("REJECTION", "반대"),
                        ],
                        db_comment="의견종류",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(blank=True, db_comment="대상ID", null=True),
                ),
                (
                    "table_name",
                    models.CharField(
                        blank=True, db_comment="테이블명", max_length=200, null=True
                    ),
                ),
                (
                    "ai_decision",
                    models.TextField(blank=True, db_comment="AI결정", null=True),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        db_comment="점수",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        db_comment="신뢰도점수",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "reasoning_summary",
                    models.TextField(blank=True, db_comment="판단근거요약", null=True),
                ),
                (
                    "risk_summary",
                    models.TextField(blank=True, db_comment="위험요약", null=True),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, db_comment="유효종료일", null=True),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        db_column="model_id",
                        db_comment="AI모델D",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="trading_discipline.aimodelrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI피드백의견",
                "verbose_name_plural": "AI피드백의견",
                "db_table": '"investment_discipline"."ai_decision_feedback"',
                "indexes": [
                    models.Index(
                        fields=["table_name", "object_id"], name="aifb_target_idx"
                    ),
                    models.Index(fields=["opinion_type"], name="aifb_opinion_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="annualinvestmentplan",
            index=models.Index(
                fields=["account", "status"], name="annual_account_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annualinvestmentplan",
            index=models.Index(
                fields=["valid_from", "valid_until"], name="annual_valid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentprinciple",
            index=models.Index(fields=["principle_type"], name="principle_type_idx"),
        ),
        migrations.AddIndex(
            model_name="quarterlyinvestmentplan",
            index=models.Index(fields=["annual_plan"], name="quarterly_annual_idx"),
        ),
        migrations.AddIndex(
            model_name="quarterlyinvestmentplan",
            index=models.Index(
                fields=["valid_from", "valid_until"], name="quarterly_valid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyinvestmentplan",
            index=models.Index(fields=["quarterly_plan"], name="monthly_quarterly_idx"),
        ),
        migrations.AddIndex(
            model_name="monthlyinvestmentplan",
            index=models.Index(
                fields=["valid_from", "valid_until"], name="monthly_valid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="security",
            index=models.Index(
                fields=["account", "is_active"], name="sec_account_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="security",
            index=models.Index(fields=["symbol"], name="sec_symbol_idx"),
        ),
        migrations.AddIndex(
            model_name="securitiesloan",
            index=models.Index(
                fields=["security", "maturity_at"], name="loan_sec_maturity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarterlyinvestmentprinciple",
            index=models.Index(
                fields=["quarterly_plan", "security"], name="qprin_plan_sec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancerecord",
            index=models.Index(
                fields=["security", "-period_end"], name="perf_sec_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancerecord",
            index=models.Index(
                fields=["period_type", "-period_end"], name="perf_type_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["security", "-executed_at"], name="order_sec_executed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["action_type"], name="order_action_idx"),
        ),
        migrations.AddIndex(
            model_name="monthlyinvestmentprinciple",
            index=models.Index(
                fields=["monthly_plan", "security"], name="mprin_plan_sec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="affectedsecurity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("market_direction", "affected_security"),
                name="affected_security_unique_alive",
            ),
        ),
        migrations.AddIndex(
            model_name="securitypricedata",
            index=models.Index(
                fields=["security", "-price_at"], name="price_sec_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingstrategy",
            index=models.Index(
                fields=["sector", "-reference_at"], name="strategy_sector_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingstrategymethod",
            index=models.Index(
                fields=["strategy", "strategy_type"], name="method_strategy_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyinvestmentplan",
            index=models.Index(
                fields=["security", "valid_from"], name="weekly_sec_valid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyinvestmentplan",
            index=models.Index(
                fields=["valid_from", "valid_until"], name="weekly_valid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyinvestmentplan",
            index=models.Index(fields=["weekly_plan"], name="daily_weekly_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyinvestmentplan",
            index=models.Index(
                fields=["valid_from", "valid_until"], name="daily_valid_idx"
            ),
        ),
    ]
