# Generated by Django 5.0.7 on 2026-08-11 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_discipline", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SecurityPriceData",
            new_name="DailySecurityPriceData",
        ),
        migrations.AlterModelOptions(
            name="dailysecuritypricedata",
            options={
                "verbose_name": "일별 가격데이터",
                "verbose_name_plural": "일별 가격데이터",
            },
        ),
        migrations.AddField(
            model_name="weeklyinvestmentplan",
            name="monthly_plan",
            field=models.ForeignKey(
                blank=True,
                db_column="monthly_plan_id",
                db_comment="월투자계획ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_plans",
                to="trading_discipline.monthlyinvestmentplan",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyinvestmentplan",
            name="security",
            field=models.ForeignKey(
                db_column="security_id",
                db_comment="종목ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_plans",
                to="trading_discipline.security",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyinvestmentplan",
            index=models.Index(
                fields=["monthly_plan", "valid_from"], name="weekly_mplan_valid_idx"
            ),
        ),
        # AlterModelTable 을 직접 쓰면 Django 가
        #   ALTER TABLE "schema"."old" RENAME TO "schema"."new"
        # 를 만들어 내는데, Postgres 는 RENAME TO 대상에 스키마 접두어를 허용하지 않아
        # `syntax error at or near "."` 로 죽는다. 그래서 실제 SQL 은 RunSQL 로 직접 쓰고,
        # 마이그레이션 상태만 AlterModelTable 로 반영한다 (state_operations).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "investment_discipline"."security_price_data" '
                    'RENAME TO "daily_security_price_data";',
                    reverse_sql='ALTER TABLE "investment_discipline"."daily_security_price_data" '
                    'RENAME TO "security_price_data";',
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="dailysecuritypricedata",
                    table='"investment_discipline"."daily_security_price_data"',
                ),
            ],
        ),
    ]
