# Generated by Django 5.0.6 on 2026-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_discipline", "0003_affected_security_news_id_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="expected_impact_from",
            field=models.DateField(blank=True, db_comment="예상영향시작일", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="expected_impact_until",
            field=models.DateField(blank=True, db_comment="예상영향종료일", null=True),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["expected_impact_from", "expected_impact_until"],
                name="news_impact_idx",
            ),
        ),
    ]
