# Generated by Django 5.0.6 on 2026-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_discipline", "0004_news_expected_impact_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyinvestmentplan",
            name="target_fill_price",
            field=models.DecimalField(
                blank=True,
                db_comment="목표체결가",
                decimal_places=2,
                max_digits=15,
                null=True,
            ),
        ),
    ]
