# Generated by Django 5.0.7 on 2026-08-18 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_discipline", "0005_daily_plan_target_fill_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="holding_quantity",
            field=models.IntegerField(
                blank=True, db_comment="기초 보유수량", null=True
            ),
        ),
        migrations.CreateModel(
            name="OrderPrincipleCheck",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                ("is_done", models.BooleanField(db_comment="준수여부")),
                (
                    "note",
                    models.TextField(blank=True, db_comment="점검메모", null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        db_comment="이행ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principle_checks",
                        to="trading_discipline.order",
                    ),
                ),
                (
                    "principle",
                    models.ForeignKey(
                        db_column="principle_id",
                        db_comment="필수원칙ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_checks",
                        to="trading_discipline.mandatoryprinciple",
                    ),
                ),
            ],
            options={
                "verbose_name": "이행원칙점검",
                "verbose_name_plural": "이행원칙점검",
                "db_table": '"investment_discipline"."order_principle_checks"',
                "ordering": ("order_id", "principle_id"),
            },
        ),
        migrations.CreateModel(
            name="MandatoryPrincipleScope",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "id",
                    models.AutoField(
                        db_comment="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAY", "일"),
                            ("WEEK", "주"),
                            ("MONTH", "월"),
                            ("QUARTER", "분기"),
                            ("YEAR", "연"),
                        ],
                        db_comment="적용기간",
                        max_length=20,
                    ),
                ),
                (
                    "principle",
                    models.ForeignKey(
                        db_column="principle_id",
                        db_comment="필수원칙ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="trading_discipline.mandatoryprinciple",
                    ),
                ),
            ],
            options={
                "verbose_name": "필수원칙적용기간",
                "verbose_name_plural": "필수원칙적용기간",
                "db_table": '"investment_discipline"."mandatory_principle_scopes"',
                "ordering": ("principle_id", "period_type"),
                "indexes": [
                    models.Index(
                        fields=["period_type"], name="mandatory_scope_period_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mandatoryprinciplescope",
            constraint=models.UniqueConstraint(
                fields=("principle", "period_type"), name="mandatory_scope_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="orderprinciplecheck",
            index=models.Index(
                fields=["principle", "is_done"], name="order_check_principle_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderprinciplecheck",
            constraint=models.UniqueConstraint(
                fields=("order", "principle"), name="order_principle_check_uniq"
            ),
        ),
    ]
