# Generated by Django 5.0.7 on 2026-08-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading_discipline",
            "0006_alter_security_holding_quantity_orderprinciplecheck_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mandatoryprinciplescope",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mandatoryprinciplescope",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="mandatoryprinciplescope",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="mandatoryprinciplescope",
            name="updated_at",
        ),
    ]
