# Generated by Django 5.0.7 on 2026-08-18 05:29
#
# 자동 생성은 Remove + Add 로 나왔는데 RenameField 로 고쳐 썼다.
# 그대로 두면 기존 행의 값이 사라진다 — 컬럼 이름만 바로잡는 변경이라 값은 남아야 한다.
# (원래 이름이 quote_price(호가) 였지만 실제로 담으려던 것은 현재가였다.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading_discipline",
            "0007_remove_mandatoryprinciplescope_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailysecuritypricedata",
            old_name="quote_price",
            new_name="current_price",
        ),
        # 컬럼 코멘트도 함께 바꾼다. 화면이 이 코멘트를 라벨로 쓰는 자리가 있다.
        migrations.AlterField(
            model_name="dailysecuritypricedata",
            name="current_price",
            field=models.DecimalField(
                blank=True,
                db_comment="현재가",
                decimal_places=2,
                max_digits=15,
                null=True,
            ),
        ),
    ]
