# Generated by Django 5.0.7 on 2026-08-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading_discipline",
            "0008_remove_dailysecuritypricedata_quote_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradingstrategy",
            options={
                "ordering": ("method_id", "strategy_type", "step_no"),
                "verbose_name": "매수매도전략",
                "verbose_name_plural": "매수매도전략",
            },
        ),
        migrations.AlterModelOptions(
            name="tradingstrategymethod",
            options={
                "verbose_name": "매수매도방법",
                "verbose_name_plural": "매수매도방법",
            },
        ),
        migrations.RemoveIndex(
            model_name="tradingstrategy",
            name="strategy_sector_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="tradingstrategymethod",
            name="method_strategy_type_idx",
        ),
        migrations.RemoveField(
            model_name="tradingstrategy",
            name="policy_name",
        ),
        migrations.RemoveField(
            model_name="tradingstrategy",
            name="price_data",
        ),
        migrations.RemoveField(
            model_name="tradingstrategy",
            name="reference_at",
        ),
        migrations.RemoveField(
            model_name="tradingstrategymethod",
            name="price_ratio",
        ),
        migrations.RemoveField(
            model_name="tradingstrategymethod",
            name="quantity_ratio",
        ),
        migrations.RemoveField(
            model_name="tradingstrategymethod",
            name="step_no",
        ),
        migrations.RemoveField(
            model_name="tradingstrategymethod",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="tradingstrategymethod",
            name="strategy_type",
        ),
        migrations.AddField(
            model_name="tradingstrategy",
            name="method",
            field=models.ForeignKey(
                blank=True,
                db_column="method_id",
                db_comment="매수매도방법ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to="trading_discipline.tradingstrategymethod",
            ),
        ),
        migrations.AddField(
            model_name="tradingstrategy",
            name="price_ratio",
            field=models.DecimalField(
                blank=True,
                db_comment="전략가격비율",
                decimal_places=2,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradingstrategy",
            name="quantity_ratio",
            field=models.DecimalField(
                blank=True,
                db_comment="전략수량비율",
                decimal_places=2,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradingstrategy",
            name="step_no",
            field=models.IntegerField(blank=True, db_comment="n차", null=True),
        ),
        migrations.AddField(
            model_name="tradingstrategy",
            name="strategy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUY_SPLIT", "분할매수"),
                    ("SELL_SPLIT", "분할매도"),
                    ("ADD_ON", "추가매수"),
                    ("TAKE_PROFIT", "익절"),
                    ("STOP_LOSS", "손절"),
                ],
                db_comment="전략종류",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradingstrategymethod",
            name="policy_name",
            field=models.CharField(
                blank=True, db_comment="정책명", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradingstrategymethod",
            name="price_data",
            field=models.ForeignKey(
                blank=True,
                db_column="price_data_id",
                db_comment="가격데이터ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="methods",
                to="trading_discipline.dailysecuritypricedata",
            ),
        ),
        migrations.AddField(
            model_name="tradingstrategymethod",
            name="reference_at",
            field=models.DateTimeField(blank=True, db_comment="기준시각", null=True),
        ),
        migrations.AddIndex(
            model_name="tradingstrategy",
            index=models.Index(
                fields=["method", "strategy_type"], name="strategy_method_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingstrategymethod",
            index=models.Index(
                fields=["sector", "-reference_at"], name="method_sector_at_idx"
            ),
        ),
    ]
