# Generated by Django 5.0.6 on 2026-08-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_comment="유저아이디",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_comment="성", max_length=100, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_comment="이름", max_length=100, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_comment="연락처", default="", max_length=30),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저",
                "db_table": "trading_discipline_management_user_profile",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(db_comment="삭제여부", default=False),
                ),
                (
                    "person_id",
                    models.AutoField(
                        db_comment="사람아이디", primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_comment="성", max_length=100, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_comment="이름", max_length=100, null=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, db_comment="지역", max_length=100, null=True
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, db_comment="생년월일", null=True),
                ),
                (
                    "death_date",
                    models.DateField(blank=True, db_comment="별세일자", null=True),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_comment="유저아이디",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사람",
                "verbose_name_plural": "사람",
                "db_table": "trading_discipline_management_person",
            },
        ),
    ]
